// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {useState, useEffect} from "react"
import { PlasmicCta } from "./plasmic/the_smb_toolkit/PlasmicCta";
import ContactButton from "./ContactButton";

const Airtable = require('airtable');

function Cta_(props, ref) {

  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [email, setEmail] = useState('')
  const [companyName, setCompanyName] = useState('')
  const [message, setMessage] = useState('')
  const [subscribed, setSubscribed] = useState(false)


  Airtable.configure({
    endpointUrl: 'https://api.airtable.com',
    apiKey: 'key5t3q3H8TgvBOMs'
  });
  var base = Airtable.base('appSy47rJWGPi4t2m');

  const url = 'https://api.airtable.com/v0/appSy47rJWGPi4t2m/tbluOldsolY4ht4ck'

  async function sendDataToAirTable() {
    await base('ContactForm').create([
      {
        "fields": {
          'FirstName': firstName,
          'LastName': lastName,
          'Email': email,
          'CompanyName': companyName,
          'Message': message,
          'Time': new Date(Date.now()).toDateString()
        }
      },

    ], function (err, records) {
      if (err) {
        console.error(err);
        return;
      }
      setFirstName('')
      setLastName('')
      setEmail('')
      setCompanyName('')
      setMessage('')
      setSubscribed(true)
      records.forEach(function (record) {
        console.log(record.getId());
      });
    });

  }



  return <PlasmicCta root={{ ref }} {...props} 
  firstName={{
    autoFocus: false,
    value: firstName,

    onChange: (e) => {
      setFirstName(e.target.value);
    },
  }}

  lastName={{
    autoFocus: false,
    value: lastName,

    onChange: (e) => {
      setLastName(e.target.value);
    },
  }}


  email={{
    autoFocus: false,
    value: email,

    onChange: (e) => {
      setEmail(e.target.value);
    },
  }}

  companyName={{
    autoFocus: false,
    value: companyName,

    onChange: (e) => {
      setCompanyName(e.target.value);
    },
  }}

  message={{
    autoFocus: false,
    value: message,

    onChange: (e) => {
      setMessage(e.target.value);
      // console.log(e.target.value)
    },
  }}

  blueContactButton={{
    onClick: () => {
      sendDataToAirTable()
      console.log('sent')
    },
    subscribed: subscribed
  }
}
  
  
  />;
}

const Cta = React.forwardRef(Cta_);

export default Cta;
