// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZXZgeU1YqYWghemcQX2Q1
// Component: UMbYnRguAf
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_the_smb_toolkit.module.css"; // plasmic-import: vZXZgeU1YqYWghemcQX2Q1/projectcss
import sty from "./PlasmicFooterLinks.module.css"; // plasmic-import: UMbYnRguAf/css

export const PlasmicFooterLinks__VariantProps = new Array();

export const PlasmicFooterLinks__ArgProps = new Array("children", "link");

function PlasmicFooterLinks__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(projectcss.all, projectcss.a, sty.link)}
        component={Link}
        href={args.link}
        platform={"nextjs"}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Contact",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </p.PlasmicLink>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooterLinks__ArgProps,
      internalVariantPropNames: PlasmicFooterLinks__VariantProps
    });

    return PlasmicFooterLinks__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterLinks";
  } else {
    func.displayName = `PlasmicFooterLinks.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterLinks = Object.assign(
  // Top-level PlasmicFooterLinks renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicFooterLinks
    internalVariantProps: PlasmicFooterLinks__VariantProps,
    internalArgProps: PlasmicFooterLinks__ArgProps
  }
);

export default PlasmicFooterLinks;
/* prettier-ignore-end */
