// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZXZgeU1YqYWghemcQX2Q1
// Component: h0X7_Kol3yFf
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: MfRpGDkJ8b4/component
import HeroButton from "../../HeroButton"; // plasmic-import: IW0QnFgF_g4/component
import Tilt from "@plasmicpkgs/react-parallax-tilt"; // plasmic-import: PfY466VIuq/codeComponent
import FunFactBox from "../../FunFactBox"; // plasmic-import: 6ql_UK2WJy/component
import TopicBox from "../../TopicBox"; // plasmic-import: 4mErNniXH-/component
import Cta from "../../Cta"; // plasmic-import: TsikC-dst8p/component
import Footer from "../../Footer"; // plasmic-import: VbkWmUKrYAc/component
import { useScreenVariants as useScreenVariantsgXe7KpKqBjNjl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gXe7KpKqBjNJL/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_the_smb_toolkit.module.css"; // plasmic-import: vZXZgeU1YqYWghemcQX2Q1/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: h0X7_Kol3yFf/css

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgXe7KpKqBjNjl()
  });

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"navAndHero"}
            data-plasmic-override={overrides.navAndHero}
            className={classNames(projectcss.all, sty.navAndHero)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames(projectcss.all, sty.hero)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__zW3Kd)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__dI66E)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___6181)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100px"
                        : "100%"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100px"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/the_smb_toolkit/images/lightbulbpng.png",
                      fullWidth: 446,
                      fullHeight: 504,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wPWy7
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"If you have "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#577EF5", fontWeight: 700 }}
                      >
                        {"the vision,"}
                      </span>
                      <React.Fragment>{"\nLet us give you "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#577EF5" }}
                      >
                        {"t"}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ color: "#577EF5", fontWeight: 700 }}
                      >
                        {"he tools."}
                      </span>
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sO2H
                  )}
                >
                  {
                    "It's frustrating as a small business owner searching the internet for business tips."
                  }
                </div>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qjsyR
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"We're on a mission to "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700, color: "#577EF5" }}
                    >
                      {"simplify the checklist"}
                    </span>
                    <React.Fragment>{" you need to "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 700, color: "#577EF5" }}
                    >
                      {"scale your business."}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </div>
              </p.Stack>

              <div className={classNames(projectcss.all, sty.freeBox__tn3Db)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uVxI)}
                >
                  <HeroButton
                    boxTitle={"For Small Businesses"}
                    className={classNames(
                      "__wab_instance",
                      sty.heroButton__kLyzD
                    )}
                    link={"/checklist-explainer"}
                    slot={"Prepare your business plan"}
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lGzy
                        )}
                      >
                        {
                          "The 101s of digital marketing, SEO, and getting your brand on the map"
                        }
                      </div>
                    }
                    slot3={"A free toolkit forever"}
                    slot4={
                      "Our SMB toolkit gives you free access to the know-hows of growing your business, particularly in the digital age we live in."
                    }
                    slot5={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3CU6F
                        )}
                      >
                        {"Access our free toolkit"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jb8Gq
                      )}
                    >
                      {"Learn how to scale your business"}
                    </div>
                  </HeroButton>

                  <HeroButton
                    boxTitle={"For Cities & Investors"}
                    className={classNames(
                      "__wab_instance",
                      sty.heroButton___7LjY3
                    )}
                    link={"/cities-and-investors"}
                    slot={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ujoyj
                        )}
                      >
                        {"Get a list of trending businesses"}
                      </div>
                    }
                    slot2={
                      "Get up-to-date information on brick-and-mortar businesses in your city"
                    }
                    slot3={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uvA6E
                        )}
                      >
                        {"Tech-powered insights"}
                      </div>
                    }
                    slot4={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0JbQm
                        )}
                      >
                        {
                          "Just like our SMB toolkit, our toolkit for cities & investors is streamlined to identify strong investments and avoid investment risks."
                        }
                      </div>
                    }
                    slot5={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6H3Wo
                        )}
                      >
                        {"Chat with us about SMBs"}
                      </div>
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___02Kqh
                      )}
                    >
                      {"Benchmark your retail strengths"}
                    </div>
                  </HeroButton>
                </p.Stack>
              </div>
            </div>
          </div>

          <div
            data-plasmic-name={"factsAboutBusinesses"}
            data-plasmic-override={overrides.factsAboutBusinesses}
            className={classNames(projectcss.all, sty.factsAboutBusinesses)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__fRmXi
              )}
            >
              {"Why a no-nonsense SMB toolkit?"}
            </div>

            <div className={classNames(projectcss.all, sty.freeBox__zevzp)}>
              <div className={classNames(projectcss.all, sty.freeBox__bDqnl)}>
                <Tilt className={classNames("__wab_instance", sty.tilt__aAzh)}>
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__fDuXv
                    )}
                    slot={"50"}
                    slot2={"of all jobs worldwide"}
                    unnamedVariant3={true}
                  >
                    {"Small businesses account for..."}
                  </FunFactBox>
                </Tilt>

                <Tilt className={classNames("__wab_instance", sty.tilt__zk67)}>
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__fovXj
                    )}
                  />
                </Tilt>

                <Tilt className={classNames("__wab_instance", sty.tilt__tu9YK)}>
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__p7Ngm
                    )}
                    slot={
                      <React.Fragment>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__x9Kdx
                          )}
                        >
                          {"3"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__y929S
                          )}
                        >
                          {"."}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___510Sc
                          )}
                        >
                          {"5"}
                        </div>
                      </React.Fragment>
                    }
                    unnamedVariant2={true}
                  >
                    {"Small businesses account for..."}
                  </FunFactBox>
                </Tilt>

                <Tilt className={classNames("__wab_instance", sty.tilt__fqaWv)}>
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__ri5I
                    )}
                    slot={"400"}
                    unnamedVariant={true}
                  />
                </Tilt>

                <Tilt
                  className={classNames("__wab_instance", sty.tilt___0MU6T)}
                >
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__l3RAi
                    )}
                    slot={"40"}
                    slot2={"of national income in emerging economies"}
                    unnamedVariant4={true}
                  >
                    {"SMEs contribute up to..."}
                  </FunFactBox>
                </Tilt>

                <Tilt className={classNames("__wab_instance", sty.tilt__hyZiC)}>
                  <FunFactBox
                    className={classNames(
                      "__wab_instance",
                      sty.funFactBox__r9M7W
                    )}
                    slot={"7"}
                    slot2={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__p0Geu
                        )}
                      >
                        {"formal jobs are generated by SMEs"}
                      </div>
                    }
                    slot3={"/10"}
                    unnamedVariant5={true}
                  >
                    {"In emerging markets,"}
                  </FunFactBox>
                </Tilt>
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jpbAo
              )}
            >
              <React.Fragment>
                <React.Fragment>{"There's "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700, color: "#577EF5" }}
                >
                  {"a lot of fluff"}
                </span>
                <React.Fragment>{" on the internet.\nWe're "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700, color: "#577EF5" }}
                >
                  {"on a mission"}
                </span>
                <React.Fragment>{" to "}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ fontWeight: 700, color: "#577EF5" }}
                >
                  {"streamline the resources"}
                </span>
                <React.Fragment>
                  {" that an SMB owner needs to scale."}
                </React.Fragment>
              </React.Fragment>
            </div>

            <p.PlasmicLink
              data-plasmic-name={"link"}
              data-plasmic-override={overrides.link}
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.__wab_text,
                sty.link
              )}
              component={Link}
              href={"/contact"}
              platform={"nextjs"}
            >
              {"Join our mission"}
            </p.PlasmicLink>
          </div>

          <div
            data-plasmic-name={"restOfPage"}
            data-plasmic-override={overrides.restOfPage}
            className={classNames(projectcss.all, sty.restOfPage)}
          >
            <div
              data-plasmic-name={"checklistDemo"}
              data-plasmic-override={overrides.checklistDemo}
              className={classNames(projectcss.all, sty.checklistDemo)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__x6MtE
                )}
              >
                {"How does it work?"}
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column__acq6H)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__e2RrX)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/the_smb_toolkit/images/mainGraphicpng.png",
                      fullWidth: 2224,
                      fullHeight: 1850,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__rqApw)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mKKuD
                    )}
                  >
                    {"We built a free, no-fluff checklist for small businesses"}
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vswZ5
                    )}
                  >
                    {
                      'It\'s hard to juggle more than one thing at once. Imagine running your own business, having to handle everything from legal and accounting to dealing with needy customers to keeping your head above water to strategize for the future.\n\nWe get it. The problem is, when we look online for resources or Google really critical steps in the business journey like "Why do people register businesses in Delaware?" or "How to put together a business plan when talking to investors?" — There just isn\'t a whole lot of good resources out there...\n\nThis project is here to fix that. We\'ve consolidated and vetted the best resources on the internet in the form of a checklist to walk business owners through step-by-step to prepare and scale their businesses. '
                    }
                  </div>
                </div>
              </p.Stack>
            </div>

            <div
              data-plasmic-name={"topicsToLearn"}
              data-plasmic-override={overrides.topicsToLearn}
              className={classNames(projectcss.all, sty.topicsToLearn)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___7KjD
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  <h3
                    data-plasmic-name={"h3"}
                    data-plasmic-override={overrides.h3}
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3
                    )}
                  >
                    {"What will you up your game on today?"}
                  </h3>
                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>

              <div className={classNames(projectcss.all, sty.freeBox__g4Qr9)}>
                <TopicBox
                  className={classNames("__wab_instance", sty.topicBox__nwSbs)}
                  slot={"Marketing"}
                  topicBoxLink={"/checklist-explainer"}
                />

                <TopicBox
                  className={classNames("__wab_instance", sty.topicBox__ocyq1)}
                  img={{
                    src: "/plasmic/the_smb_toolkit/images/legalpng.png",
                    fullWidth: 470,
                    fullHeight: 486,
                    aspectRatio: undefined
                  }}
                  slot={"Legal"}
                  topicBoxLink={"/checklist-explainer"}
                  unnamedVariant={true}
                />

                <TopicBox
                  className={classNames("__wab_instance", sty.topicBox__jj69F)}
                  img={{
                    src: "/plasmic/the_smb_toolkit/images/capitalpng.png",
                    fullWidth: 449,
                    fullHeight: 448,
                    aspectRatio: undefined
                  }}
                  slot={"Access to Capital"}
                  topicBoxLink={"/checklist-explainer"}
                  unnamedVariant2={true}
                />
              </div>
            </div>

            <Cta
              data-plasmic-name={"cta"}
              data-plasmic-override={overrides.cta}
              className={classNames("__wab_instance", sty.cta)}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navAndHero",
    "navbar",
    "hero",
    "factsAboutBusinesses",
    "link",
    "restOfPage",
    "checklistDemo",
    "columns",
    "topicsToLearn",
    "h3",
    "cta",
    "footer"
  ],

  navAndHero: ["navAndHero", "navbar", "hero"],
  navbar: ["navbar"],
  hero: ["hero"],
  factsAboutBusinesses: ["factsAboutBusinesses", "link"],
  link: ["link"],
  restOfPage: [
    "restOfPage",
    "checklistDemo",
    "columns",
    "topicsToLearn",
    "h3",
    "cta",
    "footer"
  ],

  checklistDemo: ["checklistDemo", "columns"],
  columns: ["columns"],
  topicsToLearn: ["topicsToLearn", "h3"],
  h3: ["h3"],
  cta: ["cta"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navAndHero: makeNodeComponent("navAndHero"),
    navbar: makeNodeComponent("navbar"),
    hero: makeNodeComponent("hero"),
    factsAboutBusinesses: makeNodeComponent("factsAboutBusinesses"),
    link: makeNodeComponent("link"),
    restOfPage: makeNodeComponent("restOfPage"),
    checklistDemo: makeNodeComponent("checklistDemo"),
    columns: makeNodeComponent("columns"),
    topicsToLearn: makeNodeComponent("topicsToLearn"),
    h3: makeNodeComponent("h3"),
    cta: makeNodeComponent("cta"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
