// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vZXZgeU1YqYWghemcQX2Q1
// Component: -2Xh8VfZof
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_the_smb_toolkit.module.css"; // plasmic-import: vZXZgeU1YqYWghemcQX2Q1/projectcss
import sty from "./PlasmicReadingBox.module.css"; // plasmic-import: -2Xh8VfZof/css

export const PlasmicReadingBox__VariantProps = new Array();

export const PlasmicReadingBox__ArgProps = new Array(
  "title",
  "image",
  "link",
  "description"
);

function PlasmicReadingBox__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <p.PlasmicLink
      data-plasmic-name={"link"}
      data-plasmic-override={overrides.link}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.link
      )}
      component={Link}
      href={args.link}
      platform={"nextjs"}
      target={"_blank"}
    >
      <div className={classNames(projectcss.all, sty.freeBox__rcX43)}>
        <p.PlasmicImg
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"207px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"100%"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"265px"}
          loading={"lazy"}
          src={
            args.image !== undefined
              ? args.image
              : {
                  src: "/plasmic/the_smb_toolkit/images/photo202204301431312Png.png",
                  fullWidth: 510,
                  fullHeight: 512,
                  aspectRatio: undefined
                }
          }
        />
      </div>

      <div className={classNames(projectcss.all, sty.freeBox__rGfKx)}>
        <div className={classNames(projectcss.all, sty.freeBox__bSt2B)}>
          {p.renderPlasmicSlot({
            defaultContents: "Resources loading :)",
            value: args.title,
            className: classNames(sty.slotTargetTitle)
          })}
        </div>

        <div
          data-plasmic-name={"description"}
          data-plasmic-override={overrides.description}
          className={classNames(projectcss.all, sty.description)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Loading...",
            value: args.description,
            className: classNames(sty.slotTargetDescription)
          })}
        </div>
      </div>
    </p.PlasmicLink>
  );
}

const PlasmicDescendants = {
  link: ["link", "img", "description"],
  img: ["img"],
  description: ["description"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicReadingBox__ArgProps,
      internalVariantPropNames: PlasmicReadingBox__VariantProps
    });

    return PlasmicReadingBox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "link") {
    func.displayName = "PlasmicReadingBox";
  } else {
    func.displayName = `PlasmicReadingBox.${nodeName}`;
  }
  return func;
}

export const PlasmicReadingBox = Object.assign(
  // Top-level PlasmicReadingBox renders the root element
  makeNodeComponent("link"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    description: makeNodeComponent("description"),
    // Metadata about props expected for PlasmicReadingBox
    internalVariantProps: PlasmicReadingBox__VariantProps,
    internalArgProps: PlasmicReadingBox__ArgProps
  }
);

export default PlasmicReadingBox;
/* prettier-ignore-end */
