// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicResourcesForBusinesses } from "../components/plasmic/the_smb_toolkit/PlasmicResourcesForBusinesses";
import { useEffect, useState } from "react";
import ReadingBox from "../components/ReadingBox";

function ResourcesForBusinesses() {

  const [resources, setResources] = useState([]);

  useEffect(() => {
    var airtable_url = "https://api.airtable.com/v0/appSy47rJWGPi4t2m/Resources101?api_key=" + "key5t3q3H8TgvBOMs"
    fetch(airtable_url)
      .then((res) => res.json())
      .then((resources) => {
        setResources(resources);
        console.log(resources);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);

if (resources.records) {
  return <PlasmicResourcesForBusinesses

    resources={{
      children: resources.records.map((item) => {
        return (
          <ReadingBox
            link={item.fields.URL}
            title={item.fields.Title.slice(0, 110)}
            description={item.fields.Description}
            image={item.fields.Image[0].url}
          />
        )
      })
    }}
  />
}
return <PlasmicResourcesForBusinesses />
}




export default ResourcesForBusinesses;
